My thought on the  Electric bill project
Kansoldev/SH-capstone-project-group-21 pull request #1
Opened 2022-04-25 04:56 UTC by Ngozistephen

2022-04-25 09:46 UTC, Ngozistephen commented
Thought on the chessboard project

2022-04-25 10:43 UTC, ahmadinjo reviewed
This is brilliant bro. Well done. Team lead should approve it whenever he is available. Thanks, really appreciate.

2022-04-25 10:50 UTC, Ngozistephen commented
Thank you sir. we move 👍

On Mon, 25 Apr 2022 at 11:44, Ahmad Busari ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> This is brilliant bro. Well done. Team lead should approve it whenever he
> is available. Thanks, really appreciate.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Kansoldev/SH-electricity-bill-capstone-project/pull/1#pullrequestreview-951669875>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AONNFQMDQOTR56K6XQHET53VGZZPTANCNFSM5UHLQ2GA>
> .
> You are receiving this because you authored the thread.Message ID:
> <Kansoldev/SH-electricity-bill-capstone-project/pull/1/review/951669875@
> github.com>
>

2022-04-25 11:02 UTC, ahmadinjo requested changes
- Bugs 🐛within the code that leads to calculation error for units above 150.
- Add some form of limit to the number of units a client can enter (i.e. show error for negative values). You can also restrict them from inputting negative values using the "min" attribute on the input element.
- You can the Naira (₦) symbol to the total amount.

2022-04-25 15:00 UTC, Kansoldev commented
@Ngozistephen, you have done very well, thank you for your contribution. For the chessboard project, i would merge it to the main repo but for the electricity bill, clone the repo and edit the file to have the code you wrote and submit a pull request again, make sure you apply the changes that @ahmadinjo noticed because they are important.

2022-04-25 15:02 UTC, Kansoldev approved these changes, later dismissed
Code accepted for chessboard project

2022-04-25 20:21 UTC, Ngozistephen commented
okey i will

2022-04-25 22:21 UTC, Ngozistephen commented
pls concerning the bug  have checked is working fine

2022-04-26 01:06 UTC, ahmadinjo requested changes
You've not effected the other changes I pointed out to you. Check the logic on the base master and compare it to yours. You can also implement the logic in your code too since it's supposed to be a team work.
To see the bug 🐛 I'm talking about, test 150 units and 151 units and note the difference.

2022-04-26 01:06 UTC, ahmadinjo commented on stephenthought.php
> +			$temp = (50 * $first_unit_cost) + (50 * $second_unit_cost);
NB: First 50 units at 3.50, next 100 at 4.00, next 100 at 5.20, remaining at 6.50
Check the project requirement carefully again. You can use my code as guide.

2022-04-26 01:06 UTC, ahmadinjo commented on stephenthought.php
> +			$temp = (50 * $first_unit_cost) + (50 * $second_unit_cost) + (50 * $third_unit_cost);
Same thing above applies to this. Just take your time to go through the project requirements

2022-04-26 01:06 UTC, ahmadinjo commented on stephenthought.php
> +				<input type="number" name="kwh" placeholder="Please enter no. of Units" class="form-control" />
Don't forget to add the restriction on the minimum units the client can enter

2022-04-26 20:04 UTC, closed without merging

2022-04-26 20:05 UTC, Kansoldev commented
The issue has been solved and i have merged @ahmadinjo pull request

2022-04-27 06:48 UTC, Ngozistephen commented
okey that's good